# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordproject', '0004_auto_20160331_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrecord',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
