# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordproject', '0005_wordrecord_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrecord',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
